alog/urls.py
from django.urls import path

from .views import base_views, post_views, answer_views, comment_views

app_name = 'alog'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:blogpost_id>/', base_views.detail, name='detail'),
    path('about/', base_views.about, name='about'),
    path('contact/', base_views.contact, name='contact'),

    # post_views.py
    path('post/create/', post_views.post_create, name='post_create'),
    path('post/modify/<int:blogpost_id>/', post_views.post_modify, name='post_modify'),
    path('post/delete/<int:blogpost_id>/', post_views.post_delete, name='post_delete'),

    # answer_views.py
    path('answer/create/<int:blogpost_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from alog.views import base_views 

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('alog/', include('alog.urls')),
    path('', base_views.index, name='index'),
    path('common/', include('common.urls')),
    path('accounts/', include('allauth.urls')),
]
handler404 = 'common.views.page_not_found'

alog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Blogpost(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    blogpost = models.ForeignKey(Blogpost, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    blogpost = models.ForeignKey(Blogpost, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)

alog/forms.py
from django import forms
from alog.models import Blogpost, Answer, Comment

class BlogpostForm(forms.ModelForm):
    class Meta:
        model = Blogpost
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

alog/views/answer_views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from ..models import Blogpost, Answer
from ..forms import AnswerForm

@login_required(login_url='common:login')
def answer_create(request, blogpost_id):
    """
    댓글등록
    """
    blogpost = get_object_or_404(Blogpost, pk=blogpost_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.blogpost = blogpost
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('alog:detail', blogpost_id=blogpost.id), answer.id))
    else:
        form = AnswerForm()
    context = {'blogpost': blogpost, 'form': form}
    return render(request, 'alog/post_detail.html', context)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """
    댓글수정
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('alog:detail', blogpost_id=answer.blogpost.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('alog:detail', blogpost_id=answer.blogpost.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'alog/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """
    댓글삭제
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('alog:detail', blogpost_id=answer.blogpost.id)

alog/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q
from ..models import Blogpost
import logging

logger = logging.getLogger('alog')

# Create your views here.
def index(request):
    """
    메인 첫 페이지
    """
    page = request.GET.get('page', '1') # 페이지
    kw = request.GET.get('kw', '')  # 검색어

    logger.info("INFO 레벨로 출력")
    # 조회
    post_list = Blogpost.objects.order_by('-create_date')
    if kw:
        post_list = post_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw)  # 내용검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(post_list, 10) # 10개씩
    page_obj = paginator.get_page(page)

    context = {'post_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'alog/post_list.html', context)


def detail(request, blogpost_id):
    """
    블로그 글 내용 출력
    """
    blogpost = get_object_or_404(Blogpost, pk=blogpost_id)
    context = {'blogpost': blogpost}
    return render(request, 'alog/post_detail.html', context)


def about(request):
    """
    About 페이지
    """
    context = {'about': about}
    return render(request, 'alog/about.html', context)


def contact(request):
    """
    Contact 페이지
    """
    context = {'contact': contact}
    return render(request, 'alog/contact.html', context)

alog/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import CommentForm
from ..models import Blogpost, Answer, Comment

@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    """
    alog 답글댓글등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('alog:detail', blogpost_id=comment.answer.blogpost.id), comment.id))
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'alog/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    """
    alog 답글댓글수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('alog:detail', blogpost_id=comment.answer.blogpost.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('alog:detail', blogpost_id=comment.answer.blogpost.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'alog/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    """
    alog 답글댓글삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('alog:detail', blogpost_id=comment.answer.blogpost.id)
    else:
        comment.delete()
    return redirect('alog:detail', blogpost_id=comment.answer.blogpost.id)

alog/views/post_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..models import Blogpost
from ..forms import BlogpostForm

@login_required(login_url='common:login')
def post_create(request):
    """
    블로그 글 쓰기
    """
    if request.method == 'POST':
        form = BlogpostForm(request.POST)
        if form.is_valid():
            blogpost = form.save(commit=False)
            blogpost.author = request.user
            blogpost.create_date = timezone.now()
            blogpost.save()
            return redirect('alog:index')
    else:
        form = BlogpostForm()
    context = {'form': form}
    return render(request, 'alog/post_form.html', context)


@login_required(login_url='common:login')
def post_modify(request, blogpost_id):
    """
    블로그 글 수정
    """
    blogpost = get_object_or_404(Blogpost, pk=blogpost_id)
    if request.user != blogpost.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('alog:detail', blogpost_id=blogpost.id)

    if request.method == "POST":
        form = BlogpostForm(request.POST, instance=blogpost)
        if form.is_valid():
            blogpost = form.save(commit=False)
            blogpost.author = request.user
            blogpost.modify_date = timezone.now()
            blogpost.save()
            return redirect('alog:detail', blogpost_id=blogpost.id)
    else:
        form = BlogpostForm(instance=blogpost)
    context = {'form': form}
    return render(request, 'alog/post_form.html', context)


@login_required(login_url='common:login')
def post_delete(request, blogpost_id):
    """
    블로그 글 삭제
    """
    blogpost = get_object_or_404(Blogpost, pk=blogpost_id)
    if request.user != blogpost.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('alog:detail', blogpost_id=blogpost.id)
    blogpost.delete()
    return redirect('alog:index')

templates/alog/about.html
{% extends 'base.html' %}
<head>
    {% block extrahead %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'about.css' %}">
    {% endblock %}
</head>
{% block content %}
<div class="name-profile">
    <h2>Web Developer</h2>
    <div class="introduce-profile">
        <p>코딩으로 사이트를 만드는 매력에 푹 빠져 웹 개발을 공부하고 있습니다.</p>
        <p>전공자는 아니지만 Matlab을 다루다가 코딩의 매력에 빠져서 Python으로 입문하였습니다.</p>
        <p>새로운 기술스택을 늘리는데 흥미를 느끼며 배움에 적극적입니다.</p>
        <br>
        <p>이번 블로그를 통해 처음으로 웹 배포·유지보수까지 경험하였습니다.</p>
        <p>프론트엔드와 백엔드 모두 관심을 가지고 실력을 늘리기 위해 노력하고 있습니다.</p>
        <br>
        <p>개발자 Yoonsang입니다.</p>
    </div>
</div>

<div class="skill-stack frontend">
    <h3 class="skill-title">FrontEnd Skills</h3>
    <ul class="skill-list">
        <li class="skill-item">
            <div class="skill-item-text">HTML</div>
        </li>
        <li class="skill-item">
            <div class="skill-item-text">CSS</div>
        </li>
        <li class="skill-item">
            <div class="skill-item-text">JavaScript</div>
        </li>
        <li class="skill-item">
            <div class="skill-item-text">JQuery</div>
        </li>
    </ul>
</div>

<div class="skill-stack backend">
    <h3 class="skill-title">BackEnd Skills</h3>
    <ul class="skill-list">
        <li class="skill-item">
            <div class="skill-item-text">Django</div>
        </li>
        <li class="skill-item">
            <div class="skill-item-text">Flask</div>
        </li>
        <li class="skill-item">
            <div class="skill-item-text">Node.JS</div>
        </li>
    </ul>
</div>

<div class="skill-stack other">
    <h3 class="skill-title">Other Skills</h3>
    <ul class="skill-list">
        <li class="skill-item">
            <div class="skill-item-text">Java</div>
        </li>
        <li class="skill-item">
            <div class="skill-item-text">Flutter</div>
        </li>
        <li class="skill-item">
            <div class="skill-item-text">Git</div>
        </li>
        <li class="skill-item">
            <div class="skill-item-text">AWS</div>
        </li>   
    </ul>
</div>

<div class="skill-stack ide">
    <h3 class="skill-title">Editors</h3>
    <ul class="skill-list">
        <li class="skill-item ide-item">VS CODE</li>
        <li class="skill-item ide-item">Intelli J</li>
        <li class="skill-item ide-item">Android Studio</li>
    </ul>
</div>
{% endblock %}

templates/alog/answer_form.html
{% extends 'base.html' %}
<head>
    {% load static %}
    {% block extrahead %}
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    {% endblock %}
</head>

{% block content %}
<div class="container my-3">
    <form method="POST" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/alog/comment_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control"name="content" id="content" 
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/alog/contact.html
{% extends 'base.html' %}
<head>
    {% block extrahead %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'contact.css' %}">
    {% endblock %}
</head>
{% block content %}
<div class="contact-title">
    <h1>CONTACT</h1>
</div>
<div class="contact-content">
    <ul class="contact-list">
        <li class="contact-item">
            <div class="icon">
                <img src="{% static 'img/github.svg' %}" alt="github">
            </div>
            <div class="contact-text">
                <span class="contact-text-span">
                    <h3 class="contact-text-span-title">Github</h3>
                    <h5 class="contact-text-span-subtitle">yoonsangkwak</h5>
                </span>
                <a class="contact-link" href="https://github.com/yoonsangkwak">https://github.com/yoonsangkwak</a>
            </div>
        </li>
        
        <li class="contact-item">
            <div class="icon">
                <img src="{% static 'img/blog.svg' %}" alt="blog">
            </div>
            <div class="contact-text">
                <span class="contact-text-span">
                    <h3 class="contact-text-span-title">Blog</h3>
                    <h5 class="contact-text-span-subtitle">초보개발러</h5>
                </span>
                <a class="contact-link" href="https://yoonsang-it.tistory.com/">https://yoonsang-it.tistory.com</a>
            </div>
        </li>
        
        <li class="contact-item">
            <div class="icon">
                <img src="{% static 'img/email.svg' %}" alt="email">
            </div>
            <div class="contact-text">
                <h3>Email</h3>
                <p class="contact-link">yunsag08@naver.com</p>
            </div>
        </li>
    </ul>
</div>
{% endblock %}

templates/alog/post_detail.html
{% extends 'base.html' %}
<head>
    {% load static %}
    {% block extrahead %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    {% endblock %}
</head>
{% load alog_filter %}
{% block content %}
<h1 class="detail-post-title">{{ blogpost.subject }}</h1>

<div class="detail-post-content">
    {{ blogpost.content|mark }}
</div>

{% if user.is_superuser %}
<div class="detail-post-status-btn">
    <a class="post-status-btn" href="{% url 'alog:post_modify' blogpost.id %}">수정</a>
    <a class="post-status-btn delete-link" href="#" data-uri="{% url 'alog:post_delete' blogpost.id %}">삭제</a>
</div>
{% endif %}

<h5 class="detail-post-answer">{{ blogpost.answer_set.count }}개의 댓글이 있습니다.</h5>
<div>
    <ul class="detail-post-list">
    {% for answer in blogpost.answer_set.all %}
        <a name="answer_{{ answer.id }}"></a>
        <li class="detail-post-item">
            <span class="answer-username">{{ answer.author.username }}</span>
            <span class="answer-content">{{ answer.content|mark }}</span>
            <span class="answer-text">
                <a href="{% url 'alog:comment_create_answer' answer.id  %}" class="comment-link">댓글추가</a>
            </span>
            {% if request.user == answer.author %}
            <span class="answer-text-right">
                <a href="{% url 'alog:answer_modify' answer.id %}" class="modify-link">수정</a>
            </span>
            <span class="answer-text">
                <a href="#" class="delete-link" data-uri="{% url 'alog:answer_delete' answer.id %}">삭제</a>
            </span>
            {% endif %}
        </li>
        <!-- 대댓글 -->
        {% if answer.comment_set.count > 0 %}
            <div class="comment-list">
            {% for comment in answer.comment_set.all %}
                <a name="comment_{{ comment.id }}"></a>
                <div class="comment-item">
                    <span class="comment-author">↳ {{ comment.author }}</span>
                    <span class="comment-content">{{ comment.content }}</span>
                    <span class="comment-date answer-text-right">{{ comment.create_date }}</span>
                    {% if request.user == comment.author %}
                    <span class="answer-text">
                        <a href="{% url 'alog:comment_modify_answer' comment.id  %}" class="modify-link">수정</a>
                    </span>
                    <span class="answer-text">
                        <a href="#" class="delete-link" data-uri="{% url 'alog:comment_delete_answer' comment.id  %}">삭제</a>
                    </span>
                    {% endif %}
                </div>
            {% endfor %}
            </div>
            {% endif %}
    {% endfor %}
    </ul>
</div>

<form action="{% url 'alog:answer_create' blogpost.id %}" method="POST">
    {% csrf_token %}
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
    {% for field in form %}
        {% if field.errors %}
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
        {% endif %}
    {% endfor %}
    </div>
    {% endif %}
    {% if not user.is_authenticated %}
    <div class="detail-submit-disabled">
        <a class="detail-to-login" href="{% url 'common:login' %}">로그인 후 이용하세요</a>
    </div>
    {% else %}
    <div class="detail-submit-box">
        <textarea name="content" id="content" rows="15"></textarea>
        <input class="submit" type="submit" value="댓글등록">
    </div>
    {% endif %}
</form>
{% endblock %}
{% block extra-script %}
<script src="{% static 'jquery-3.5.1.min.js' %}"></script>
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete-link").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

templates/alog/post_form.html
{% extends 'base.html' %}
<head>
    {% block extrahead %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    {% endblock %}
</head>

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">블로그 글 등록</h5>
    <form method="POST" class="post-form my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/alog/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if post_list %}
    <div class="row justify-content-end my-3">
        <div class="col-4 input-group" id="search-div">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-primary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
    <ul class="card-list">
    {% for blogpost in post_list %}
        <li class="card-item">
            <a href="{% url 'alog:detail' blogpost.id %}"><figure class="card-image"></figure></a>
            <div class="card-desc">
                <a class="link post-title" href="{% url 'alog:detail' blogpost.id %}">{{ blogpost.subject }}</a>
                <p class="date">{{ blogpost.create_date }}</p>
                <p class="writer">YoonSang</p>
            </div>
        </li>
    {% endfor %}
    </ul>
    {% if user.is_superuser %}
    <div class="goto-write">
        <a class="goto-write-btn" href="{% url 'alog:post_create' %}">글쓰기</a>
    </div>
    {% endif %}
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if post_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="{{ post_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in post_list.paginator.page_range %}
        {% if page_number >= post_list.number|add:-5 and page_number <= post_list.number|add:5 %}
            {% if page_number == post_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if post_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <form id="searchForm" method="get" action="{% url 'index' %}">
        <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
        <input type="hidden" id="page" name="page" value="{{ page }}">
    </form>
{% else %}
    <p>게시된 글이 없습니다.</p>
{% endif %}
{% endblock %}
{% block script %}
<script type="text/javascript">
$(document).ready(function() {
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });
    
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}