alog/urls.py
from django.urls import path

from .views import base_views, post_views, answer_views, comment_views

app_name = 'alog'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:blogpost_id>/', base_views.detail, name='detail'),
    path('about/', base_views.about, name='about'),
    path('contact/', base_views.contact, name='contact'),

    # post_views.py
    path('post/create/', post_views.post_create, name='post_create'),
    path('post/modify/<int:blogpost_id>/', post_views.post_modify, name='post_modify'),
    path('post/delete/<int:blogpost_id>/', post_views.post_delete, name='post_delete'),

    # answer_views.py
    path('answer/create/<int:blogpost_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from alog.views import base_views 

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('alog/', include('alog.urls')),
    path('', base_views.index, name='index'),
    path('common/', include('common.urls')),
    path('accounts/', include('allauth.urls')),
]
handler404 = 'common.views.page_not_found'

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="Email")

    class Meta:
        model = User
        fields = ("username", "email")

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm

# Create your views here.
def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})


def page_not_found(request, exception):
    """
    404 Page not found
    """
    return render(request, 'common/404.html', {})

templates/common/login.html
{% extends "base.html" %}
{% load socialaccount %}
<head> 
    {% load static %}
    {% block extrahead %}
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'login.css' %}">
    {% endblock %}
</head>
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>
    <form method="POST" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="text" value="{{ next }}">
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 ID</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
    <div class="social-login">
        <p class="social-login-text">소셜 계정으로 간편 로그인하기</p>
        <a class="social-login-item" href="{% provider_login_url 'google' method='oauth2' %}">
            <img src="{% static 'img/google_login.png' %}" alt="google-login">
        </a>
        <a class="social-login-item" href="{% provider_login_url 'facebook' method='oauth2' %}">
            <img src="{% static 'img/facebook_login.png' %}" alt="facebook-login">
        </a>
        <a class="social-login-item" href="{% provider_login_url 'naver' method='oauth2' %}">
            <img src="{% static 'img/naver_login.png' %}" alt="naver-login">
        </a>
    </div>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
<head> 
    {% load static %}
    {% block extrahead %}
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    {% endblock %}
</head>
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1"">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1" value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2" value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email"">이메일</label>
            <input type="text" class="form-control" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}