alog/urls.py
from django.urls import path

from .views import base_views, post_views, answer_views, comment_views

app_name = 'alog'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:blogpost_id>/', base_views.detail, name='detail'),
    path('about/', base_views.about, name='about'),
    path('contact/', base_views.contact, name='contact'),

    # post_views.py
    path('post/create/', post_views.post_create, name='post_create'),
    path('post/modify/<int:blogpost_id>/', post_views.post_modify, name='post_modify'),
    path('post/delete/<int:blogpost_id>/', post_views.post_delete, name='post_delete'),

    # answer_views.py
    path('answer/create/<int:blogpost_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from alog.views import base_views 

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('alog/', include('alog.urls')),
    path('', base_views.index, name='index'),
    path('common/', include('common.urls')),
    path('accounts/', include('allauth.urls')),
]
handler404 = 'common.views.page_not_found'

alog/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q
from ..models import Blogpost
import logging

logger = logging.getLogger('alog')

# Create your views here.
def index(request):
    """
    메인 첫 페이지
    """
    page = request.GET.get('page', '1') # 페이지
    kw = request.GET.get('kw', '')  # 검색어

    logger.info("INFO 레벨로 출력")
    # 조회
    post_list = Blogpost.objects.order_by('-create_date')
    if kw:
        post_list = post_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw)  # 내용검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(post_list, 10) # 10개씩
    page_obj = paginator.get_page(page)

    context = {'post_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'alog/post_list.html', context)


def detail(request, blogpost_id):
    """
    블로그 글 내용 출력
    """
    blogpost = get_object_or_404(Blogpost, pk=blogpost_id)
    context = {'blogpost': blogpost}
    return render(request, 'alog/post_detail.html', context)


def about(request):
    """
    About 페이지
    """
    context = {'about': about}
    return render(request, 'alog/about.html', context)


def contact(request):
    """
    Contact 페이지
    """
    context = {'contact': contact}
    return render(request, 'alog/contact.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Alog CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'default.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    {% block extrahead %}
    {% endblock %}
    <title>Alog</title>
</head>
<body>
    <div class="page">
        {% include 'navbar.html' %}
        
        <section class="section" id="section">
            {% block content %}
            {% endblock %}
        </section>

        <footer class="footer">
            <div class="footer-content">
                Copyright 2020 © Yoonsang
            </div>
        </footer>
    </div>
    <script src="{% static 'main.js' %}"></script>
    <script src="{% static 'jquery-3.5.1.min.js' %}"></script>
    {% block script %}
    {% endblock %}
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<header class="header">
    <div class="global-nav">
        <a href="{% url 'alog:index' %}" class="web-title link">Alog</a>
        <button class="menu-button">
            <div class="line"></div>
            <div class="line"></div>
            <div class="line"></div>
        </button>
    </div>
    
    <div class="local-nav">
        <ul class="menu">
            <li class="menu-item">
                <a href="{% url 'alog:index' %}" class="link">HOME</a>
            </li>
            <li class="menu-item">
                <a href="{% url 'alog:about' %}" class="link">ABOUT</a>
            </li>
            <li class="menu-item">
                <a href="{% url 'alog:contact' %}" class="link">CONTACT</a>
            </li>
            <li class="menu-item">
                {% if user.is_authenticated %}
                <a href="{% url 'common:logout' %}" class="link">LOGOUT</a>
                {% else %}
                <a href="{% url 'common:login' %}" class="link">LOGIN</a>
                {% endif %}
            </li>
        </ul>
    </div>
</header>
<div class="cover-img"></div>